server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/mooni9375/trade-insurance-system-config.git
          default-label: main
          search-paths: /

logging:
  level:
    web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"